blank_issues_enabled: false
contact_links:
  - name: "Search existing issues"
    url: https://github.com/Osasuwu/like_spotify_mobile_app/issues
    about: "Check existing issues before creating a new one"
